apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmos
  namespace: farmos
  labels:
    app: farmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmos
  template:
    metadata:
      labels:
        app: farmos
    spec:
      containers:
      - name: farmos
        image: jorblad/farmos-k8s:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: farmos-db-secret
              key: database_url
        - name: FARMOS_DB_NAME
          value: "farmos"
        - name: FARMOS_DB_USER
          valueFrom:
            secretKeyRef:
              name: farmos-db-secret
              key: username
        - name: FARMOS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: farmos-db-secret
              key: password
        - name: FARMOS_DB_HOST
          value: "farmos-db"
        volumeMounts:
        - mountPath: /opt/drupal/web/sites
          name: farmos-sites-volume
      volumes:
      - name: farmos-sites-volume
        persistentVolumeClaim:
          claimName: farmos-sites-pvc
