apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmos
  namespace: farmos
  labels:
    app: farmos
spec:
  replicas: 0
  selector:
    matchLabels:
      app: farmos
  template:
    metadata:
      labels:
        app: farmos
    spec:
      initContainers:
      - name: farmos-init
        image: jorblad/farmos-k8s:v3.4.5.4
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          cd /opt/drupal/web && \
          ./drupal_fix_permissions.sh -u=www-data && \
          drush updb --yes && \
          drush cr
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: uri
        - name: FARMOS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: dbname
        - name: FARMOS_DB_USER
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: username
        - name: FARMOS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: password
        - name: FARMOS_DB_HOST
          value: "farmos-db"
        volumeMounts:
        - mountPath: /opt/drupal/web/sites
          name: farmos-sites-volume
      containers:
      - name: farmos
        image: jorblad/farmos-k8s:v3.4.5.4
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: uri
        - name: FARMOS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: dbname
        - name: FARMOS_DB_USER
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: username
        - name: FARMOS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: farmos-db-app
              key: password
        - name: FARMOS_DB_HOST
          value: "farmos-db"
        volumeMounts:
        - mountPath: /opt/drupal/web/sites
          name: farmos-sites-volume
      volumes:
      - name: farmos-sites-volume
        persistentVolumeClaim:
          claimName: farmos-sites-pvc
