apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: farmos-db
  namespace: farmos
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 2 # Number of PostgreSQL replicas
  enableSuperuserAccess: true
  # Use ImageCatalog major selection for controlled upgrades and stable image resolution.
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql-farmos
    major: 17
  managed:
    roles:
    - name: farmos
      superuser: true
      login: true

    - name: app
      superuser: true
      login: true

  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
  monitoring:
    enablePodMonitor: true
  primaryUpdateStrategy: unsupervised
