apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: farmos-db
  namespace: farmos
spec:
  instances: 2 # Number of PostgreSQL replicas
  enableSuperuserAccess: true
  # CNPG major upgrades must be done one major at a time (16 -> 17 -> 18).
  imageName: ghcr.io/cloudnative-pg/postgresql:17.3
  managed:
    roles:
    - name: farmos
      superuser: true
      login: true

    - name: app
      superuser: true
      login: true

  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
  monitoring:
    enablePodMonitor: true
  primaryUpdateStrategy: unsupervised
