apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farmos-sites-pvc
  namespace: farmos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
