apiVersion: v1
kind: Service
metadata:
  name: farmos-svc
  namespace: farmos
  labels:
    app: farmos
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.254.19
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: farmos
